name: Main Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      breadth:
        type: number
        default: 2
      max-depth:
        type: number
        default: 1
      website-url:
        type: string
        default: "https://kzmkgze3v46fyc6paipj.lite.vusercontent.net/login"
      username:
        type: string
      password:
        type: string

jobs:
  generate:
    uses: ./.github/workflows/generate.yml
    with:
      dispatchId: manual-${{ github.run_id }}
      breadth: ${{ fromJson(inputs.breadth) }}
      max-depth: ${{ fromJson(inputs.max-depth) }}
      website-url: ${{ inputs.website-url }}
      login_username: ${{ inputs.username }}
      login_password: ${{ inputs.password }}
    secrets:
      TESTDRIVER_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

