name: Main Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      depth:
        type: number
        default: 1
      max-depth:
        type: number
        default: 1
      website-url:
        type: string
        default: "https://kzmin4o8zlrumvqikugo.lite.vusercontent.net/login"
      username:
        type: string
      password:
        type: string

jobs:
  generate:
    uses: ./.github/workflows/generate.yml
    with:
      dispatchId: manual-${{ github.run_id }}
      depth: ${{ fromJson(inputs.depth) }}
      max-depth: ${{ fromJson(inputs.max-depth) }}
    secrets:
      TESTDRIVER_API_KEY: ${{ secrets.TESTDRIVER_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOGIN_USERNAME: ${{ inputs.username }}
      LOGIN_PASSWORD: ${{ inputs.password }}

